version: '3.2'

services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      
      - ./build:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"